//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncMLViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("taken from: http://openmobilealliance.org/release/Common/V1_2_2-20090724-A/OMA-TS" +
            "-SyncML-RepPro-V1_2_2-20090724-A.pdf\r\n\r\nInformational 1xx\r\n\r\n101\r\n\r\nIn progress." +
            " The specified SyncML command is being carried out, but has not yet completed.\\r" +
            "\\n\r\n\r\n\r\nSuccessful 2xx\r\n\r\n200\r\nOK. The SyncML command completed successfully.\r\n\r" +
            "\n201\r\n\r\nItem added. The requested item was added.\r\n\r\n202\r\n\r\nAccepted for process" +
            "ing. The request to either run a remote execution of an application or to alert " +
            "a user or application was successfully performed.\r\n\r\n203\r\n\r\nNon-authoritative re" +
            "sponse. The request is being responded to by an entity other than the one target" +
            "ed. The response is only to be returned when the request would have been resulte" +
            "d in a 200 response code from the authoritative target.\r\n\r\n204\r\n\r\nNo content. Th" +
            "e request was successfully completed but no data is being returned. The response" +
            " code is also returned in response to a Get when the target has no content.\r\n\r\n2" +
            "05\r\n\r\nReset content. The source SHOULD update their content. The originator of t" +
            "he request is being told that their content SHOULD be synchronized to get an up " +
            "to date version.\r\n\r\n206\r\n\r\nPartial content. The response indicates that only par" +
            "t of the command was completed. If the remainder of the command can be completed" +
            " later, then when completed another appropriate completion request status code S" +
            "HOULD be created.\r\n\r\n207\r\n\r\nConflict resolved with merge. The response indicates" +
            " that the request created a conflict; which was resolved with a merge of the cli" +
            "ent and server instances of the data. The response includes both the Target and " +
            "Source URLs in the Item of the Status. In addition, a Replace command is returne" +
            "d with the merged data.\r\n\r\n208\r\n\r\nConflict resolved with client’s command \"winni" +
            "ng\". The response indicates that there was an update conflict; which was resolve" +
            "d by the client command winning. \r\n\r\n209\r\n\r\nConflict resolved with duplicate. Th" +
            "e response indicates that the request created an update conflict; which was reso" +
            "lved with a duplication of the client’s data being created in the server databas" +
            "e.\r\nThe response includes both the target URI of the duplicate in the Item of th" +
            "e Status. In addition, in the case of a two-way synchronization, an Add command " +
            "is returned with the duplicate data definition.\r\n\r\n210\r\n\r\nDelete without archive" +
            ". The response indicates that the requested data was successfully deleted, but t" +
            "hat it was not archived prior to deletion because this OPTIONAL feature was not " +
            "supported by the implementation.\r\n\r\n211\r\n\r\nItem not deleted. The requested item " +
            "was not found. It could have been previously deleted.\r\n\r\n212\r\n\r\nAuthentication a" +
            "ccepted. No further authentication is needed for the remainder of the synchroniz" +
            "ation session. This response code can only be used in response to a request in w" +
            "hich the credentials were provided.\r\n\r\n213\r\n\r\nChunked item accepted and buffered" +
            ".\r\n\r\n214\r\n\r\nOperation cancelled. The SyncML command completed successfully, but " +
            "no more commands will be processed within the session.\r\n\r\n215\r\n\r\nNot executed. A" +
            " command was not executed, as a result of user interaction and user chose not to" +
            " accept the choice.\r\n\r\n216\r\n\r\nAtomic roll back OK. A command was inside Atomic e" +
            "lement and Atomic failed. This command was rolled back successfully.\r\n\r\n\r\nRedire" +
            "ction 3xx\r\n\r\n300\r\n\r\nMultiple choices. The requested target is one of a number of" +
            " multiple alternatives requested target. The alternative SHOULD also be returned" +
            " in the Item element type in the Status.\r\n\r\n301\r\n\r\nMoved permanently. The reques" +
            "ted target has a new URI. The new URI SHOULD also be returned in the Item elemen" +
            "t type in the Status.\r\n\r\n302\r\n\r\nFound. The requested target has temporarily move" +
            "d to a different URI. The original URI SHOULD continue to be used. The URI of th" +
            "e temporary location SHOULD also be returned in the Item element type in the Sta" +
            "tus. The requestor SHOULD confirm the identity and authority of the temporary UR" +
            "I to act on behalf of the original target URI.\r\n\r\n303\r\n\r\nSee other. The requeste" +
            "d target can be found at another URI. The other URI SHOULD be returned in the It" +
            "em element type in the Status.\r\n\r\n304\r\n\r\nNot modified. The requested SyncML comm" +
            "and was not executed on the target. This is an additional response that can be a" +
            "dded to any of the other Redirection response codes.\r\n\r\n305\r\n\r\nUse proxy. The re" +
            "quested target MUST be accessed through the specified proxy URI. The proxy URI S" +
            "HOULD also be returned in the Item element type in the Status.\r\n\r\n\r\nOriginator E" +
            "xceptions 4xx\r\n\r\n400\r\n\r\nBad request. The requested command could not be performe" +
            "d because of malformed syntax in the command. The malformed command MAY also be " +
            "returned in the Item element type in the Status.\r\n\r\n401\r\n\r\nInvalid credentials. " +
            "The requested command failed because the requestor MUST provide proper authentic" +
            "ation. If the property type of authentication was presented in the original requ" +
            "est, then the response code indicates that the requested command has been refuse" +
            "d for those credentials.\r\n\r\n402\r\n\r\nPaymentneeded. The requested command failed b" +
            "ecause proper payment isneeded. This version of SyncML does not standardize the " +
            "payment mechanism.\r\n\r\n403\r\n\r\nForbidden. The requested command failed, but the re" +
            "cipient understood the requested command. Authentication will not help and the r" +
            "equest SHOULD NOT be repeated. If the recipient wishes to make public why the re" +
            "quest was denied, then a description MAY be specified in the Item element type i" +
            "n the Status. If the recipient does not wish to make public why the request was " +
            "denied then the response code 404 MAY be used instead.\r\n\r\n404\r\n\r\nNot found. The " +
            "requested target was not found. No indication is given as to whether this is a t" +
            "emporary or permanent condition. The response code 410 SHOULD be used when the c" +
            "ondition is permanent and the recipient wishes to make this fact public. This re" +
            "sponse code is also used when the recipient does not want to make public the rea" +
            "son for why a requested command is not allowed or when no other response code is" +
            " appropriate.\r\n\r\n405\r\n\r\nCommand not allowed. The requested command is not allowe" +
            "d on the target. The recipient SHOULD return the allowed command for the target " +
            "in the Item element type in the Status.\r\n\r\n406\r\n\r\nOptional feature not supported" +
            ". The requested command failed because an OPTIONAL feature in the request was no" +
            "t supported. The unsupported feature SHOULD be specified by the Item element typ" +
            "e in the Status.\r\n\r\n407\r\n\r\nMissing credentials. This response code is similar to" +
            " 401 except that the response code indicates that the originator MUST first auth" +
            "enticate with the recipient. The recipient SHOULD also return the suitable chall" +
            "enge in the Chal element type in the Status.\r\n\r\n408\r\n\r\nRequest timeout. An expec" +
            "ted message was not received within the REQUIRED period of time. The request can" +
            " be repeated at another time. The RespURI can be used to specify the URI and opt" +
            "ionally the date/time after which the originator can repeat the request. See Res" +
            "pURI for details. \r\n\r\n409\r\n\r\nConflict. The requested failed because of an update" +
            " conflict between the client and server versions of the data. Setting of the con" +
            "flict resolution policy is outside the scope of this version of SyncML. However," +
            " identification of conflict resolution performed, if any, is within the scope.\r\n" +
            "\r\n410\r\n\r\nGone. The requested target is no longer on the recipient and no forward" +
            "ing URI is known.\r\n\r\n411\r\n\r\nSizeREQUIRED. The requested command MUST be accompan" +
            "ied by byte size or length information in the Meta element type.\r\n\r\n412\r\n\r\nIncom" +
            "plete command. The requested command failed on the recipient because it was inco" +
            "mplete or incorrectly formed. The recipient SHOULD specify the portion of the co" +
            "mmand that was incomplete or incorrect in the Item element type in the Status.\r\n" +
            "\r\n413\r\n\r\nRequest entity too large. The recipient is refusing to perform the requ" +
            "ested command because the requested item is larger than the recipient is able or" +
            " willing to process. If the condition is temporary, the recipient SHOULD also in" +
            "clude a Status with the response code 418 and specify a RespURI with the respons" +
            "e URI and optionally the date/time that the command SHOULD be repeated.\r\n\r\n414\r\n" +
            "\r\nURI too long. The requested command failed because the target URI is too long " +
            "for what the recipient is able or willing to process. This response code is seld" +
            "om encountered, but is used when a recipient perceives that an intruder might be" +
            " attempting to exploit security holes or other defects in order to threaten the " +
            "recipient.\r\n\r\n415\r\n\r\nUnsupported media type or format. The unsupported content t" +
            "ype or format SHOULD also be identified in the Item element type in the Status.\r" +
            "\n\r\n416\r\n\r\nRequested size too big. The request failed because the specified byte " +
            "size in the request was too big.\r\n\r\n417\r\n\r\nRetry later. The request failed at th" +
            "is time and the originator SHOULD retry the request later. The recipient SHOULD " +
            "specify a RespURI with the response URI and the date/time that the command SHOUL" +
            "D be repeated.\r\n\r\n418\r\n\r\nAlready exists. The requested Put or Add command failed" +
            " because the target already exists.\r\n\r\n419\r\n\r\nConflict resolved with server data" +
            ". The response indicates that the client request created a conflict; which was r" +
            "esolved by the server command winning. The normal information in the Status SHOU" +
            "LD be sufficient for the client to \"undo\" the resolution, if it is desired.\r\n\r\n4" +
            "20\r\n\r\nDevice full. The response indicates that the recipient has no more storage" +
            " space for the remaining synchronization data. The response includes the remaini" +
            "ng number of data that could not be returned to the originator in the Item of th" +
            "e Status.\r\n\r\n421\r\n\r\nUnknown search grammar. The requested command failed on the " +
            "server because the specified search grammar was not known. The client SHOULD re-" +
            "specify the search using a known search grammar. \r\n\r\n422\r\n\r\nBad CGI Script. The " +
            "requested command failed on the server because the CGI scripting in the LocURI w" +
            "as incorrectly formed. The client SHOULD re-specify the portion of the command t" +
            "hat was incorrect in the Item element type in the Status.\r\n\r\n423\r\n\r\nSoft-delete " +
            "conflict. The requested command failed because the \"Soft Deleted\" item was previ" +
            "ously \"Hard Deleted\" on the server.\r\n\r\n424\r\n\r\nSize mismatch. The chunked object " +
            "was received, but the size of the received object did not match the size declare" +
            "d within the first chunk.\r\n\r\n425\r\n\r\nPermission Denied. The requested command fai" +
            "led because the sender does not have adequate access control permissions (ACL) o" +
            "n the recipient.\r\n\r\n426\r\n\r\nPartial item not accepted. Receiver of status code MA" +
            "Y resend the whole item in next package.\r\n\r\n427\r\n\r\nItem Not empty. Parent cannot" +
            " be deleted since it contains children.\r\n\r\n428\r\n\r\nMove Failed\r\n\r\n\r\nRecipient Exc" +
            "eption 5xx\r\n\r\n500\r\n\r\nCommand failed. The recipient encountered an unexpected con" +
            "dition which prevented it from fulfilling the request\r\n\r\n501\r\n\r\nCommand not impl" +
            "emented. The recipient does not support the\r\n\r\n \r\n\r\ncommand REQUIRED to fulfill " +
            "the request. This is the appropriate response when the recipient does not recogn" +
            "ize the requested command and is not capable of supporting it for any resource.\r" +
            "\n\r\n502\r\n\r\nBad gateway. The recipient, while acting as a gateway or proxy, receiv" +
            "ed an invalid response from the upstream recipient it accessed in attempting to " +
            "fulfill the request.\r\n\r\n503\r\n\r\nService unavailable. The recipient is currently u" +
            "nable to handle the request due to a temporary overloading or maintenance of the" +
            " recipient. The implication is that this is a temporary condition; which will be" +
            " alleviated after some delay. The recipient SHOULD specify the URI and date/time" +
            " after which the originator SHOULD retry in the RespURI in the response.\r\n\r\n504\r" +
            "\n\r\nGateway timeout. The recipient, while acting as a gateway or proxy, did not r" +
            "eceive a timely response from the upstream recipient specified by the URI (e.g. " +
            "HTTP, FTP, LDAP) or some other auxiliary recipient (e.g. DNS) it needed to acces" +
            "s in attempting to complete the request.\r\n\r\n505\r\n\r\nDTD Version not supported. Th" +
            "e recipient does not support or refuses to support the specified version of Sync" +
            "ML DTD used in the request SyncML Message. The recipient MUST include the versio" +
            "ns it does support in the Item element type in the Status.\r\n\r\n506\r\n\r\nProcessing " +
            "error. An application error occurred while processing the request. The originato" +
            "r SHOULD retry the request. The RespURI can contain the URI and date/time after " +
            "which the originator can retry the request.\r\n\r\n507\r\n\r\nAtomic failed. The error c" +
            "aused all SyncML commands within an Atomic element type to fail.\r\n\r\n508\r\n\r\nRefre" +
            "sh REQUIRED. An error occurred that necessitates a refresh of the current synchr" +
            "onization state of the client with the server. Client is requested to initiate t" +
            "he session type specified in the server’s ALERT (which is included in the same p" +
            "ackage as the Status 508). The only valid values for this ALERT are either a slo" +
            "w sync (201) or a refresh with the server.\r\n\r\n509\r\n\r\nReserved for future use.\r\n\r" +
            "\n510\r\n\r\nData store failure. An error occurred while processing the request. The " +
            "error is related to a failure in the recipient data store.\r\n\r\n511\r\n\r\nServer fail" +
            "ure. A severe error occurred in the server while processing the request. The ori" +
            "ginator SHOULD NOT retry the request.\r\n\r\n512\r\n\r\nSynchronization failed. An appli" +
            "cation error occurred during the synchronization session. The originator SHOULD " +
            "restart the synchronization session from the beginning.\r\n\r\n513\r\n\r\nProtocol Versi" +
            "on not supported. The recipient does not support or refuses to support the speci" +
            "fied version of the SyncML Synchronization Protocol used in the request SyncML M" +
            "essage. The recipient MUST include the versions it does support in the Item elem" +
            "ent type in the Status.\r\n\r\n514\r\n\r\nOperation cancelled. The SyncML command was no" +
            "t completed successfully, since the operation was already cancelled before proce" +
            "ssing the command. The originator SHOULD repeat the command in the next session." +
            "\r\n\r\n516\r\n\r\nAtomic roll back failed. Command was inside Atomic element and Atomic" +
            " failed. This command was not rolled back successfully. Server SHOULD take actio" +
            "n to try to recover client back into original state.\r\n\r\n517\r\n\r\nAtomic response t" +
            "oo large to fit. The response to an atomic command was too large to fit in a sin" +
            "gle message.\r\n\r\n\r\nApplication specific codes 1xxx\r\n\r\n1000 – 1999\r\n\r\nThese status" +
            " codes are application specific status codes and the meanings of these are not d" +
            "efined in this specification. \r\n\r\nIt is recommended to define status codes with " +
            "the same grouping as above within this application specific interval but it is t" +
            "he application that defines the allowed values:\r\n\r\nInformational               1" +
            "1xx\r\nSuccessful                  12xx\r\nRedirection                 13xx\r\nOrigina" +
            "tor Exceptions       14xx\r\nRecipient Exception         15xx")]
        public string StatusCodes {
            get {
                return ((string)(this["StatusCodes"]));
            }
            set {
                this["StatusCodes"] = value;
            }
        }
    }
}
