//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SyncMLViewer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.2.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Info taken from official OMA SyncML documentation here: \r\nhttp://openmobileallian" +
            "ce.org/release/Common/V1_2_2-20090724-A/OMA-TS-SyncML-RepPro-V1_2_2-20090724-A.p" +
            "df\r\n\r\nUse [Ctrl] + [F] to use search to find a particular status code.\r\n\r\n\r\n\r\n--" +
            "Informational (1xx)\r\n\r\n101\r\nIn progress. The specified SyncML command is being c" +
            "arried out, but has not yet completed.\r\n\r\n\r\n\r\n--Successful (2xx)\r\n\r\n200\r\nOK. The" +
            " SyncML command completed successfully.\r\n\r\n201\r\nItem added. The requested item w" +
            "as added.\r\n\r\n202\r\nAccepted for processing. The request to either run a remote ex" +
            "ecution of an application or to alert a user or application was successfully per" +
            "formed.\r\n\r\n203\r\nNon-authoritative response. The request is being responded to by" +
            " an entity other than the one targeted. The response is only to be returned when" +
            " the request would have been resulted in a 200 response code from the authoritat" +
            "ive target.\r\n\r\n204\r\nNo content. The request was successfully completed but no da" +
            "ta is being returned. The response code is also returned in response to a Get wh" +
            "en the target has no content.\r\n\r\n205\r\nReset content. The source SHOULD update th" +
            "eir content. The originator of the request is being told that their content SHOU" +
            "LD be synchronized to get an up to date version.\r\n\r\n206\r\nPartial content. The re" +
            "sponse indicates that only part of the command was completed. If the remainder o" +
            "f the command can be completed later, then when completed another appropriate co" +
            "mpletion request status code SHOULD be created.\r\n\r\n207\r\nConflict resolved with m" +
            "erge. The response indicates that the request created a conflict; which was reso" +
            "lved with a merge of the client and server instances of the data. The response i" +
            "ncludes both the Target and Source URLs in the Item of the Status. In addition, " +
            "a Replace command is returned with the merged data.\r\n\r\n208\r\nConflict resolved wi" +
            "th client’s command \"winning\". The response indicates that there was an update c" +
            "onflict; which was resolved by the client command winning. \r\n\r\n209\r\nConflict res" +
            "olved with duplicate. The response indicates that the request created an update " +
            "conflict; which was resolved with a duplication of the client’s data being creat" +
            "ed in the server database. The response includes both the target URI of the dupl" +
            "icate in the Item of the Status. In addition, in the case of a two-way synchroni" +
            "zation, an Add command is returned with the duplicate data definition.\r\n\r\n210\r\nD" +
            "elete without archive. The response indicates that the requested data was succes" +
            "sfully deleted, but that it was not archived prior to deletion because this OPTI" +
            "ONAL feature was not supported by the implementation.\r\n\r\n211\r\nItem not deleted. " +
            "The requested item was not found. It could have been previously deleted.\r\n\r\n212\r" +
            "\nAuthentication accepted. No further authentication is needed for the remainder " +
            "of the synchronization session. This response code can only be used in response " +
            "to a request in which the credentials were provided.\r\n\r\n213\r\nChunked item accept" +
            "ed and buffered.\r\n\r\n214\r\nOperation cancelled. The SyncML command completed succe" +
            "ssfully, but no more commands will be processed within the session.\r\n\r\n215\r\nNot " +
            "executed. A command was not executed, as a result of user interaction and user c" +
            "hose not to accept the choice.\r\n\r\n216\r\nAtomic roll back OK. A command was inside" +
            " Atomic element and Atomic failed. This command was rolled back successfully.\r\n\r" +
            "\n\r\n\r\n--Redirection (3xx)\r\n\r\n300\r\nMultiple choices. The requested target is one o" +
            "f a number of multiple alternatives requested target. The alternative SHOULD als" +
            "o be returned in the Item element type in the Status.\r\n\r\n301\r\nMoved permanently." +
            " The requested target has a new URI. The new URI SHOULD also be returned in the " +
            "Item element type in the Status.\r\n\r\n302\r\nFound. The requested target has tempora" +
            "rily moved to a different URI. The original URI SHOULD continue to be used. The " +
            "URI of the temporary location SHOULD also be returned in the Item element type i" +
            "n the Status. The requestor SHOULD confirm the identity and authority of the tem" +
            "porary URI to act on behalf of the original target URI.\r\n\r\n303\r\nSee other. The r" +
            "equested target can be found at another URI. The other URI SHOULD be returned in" +
            " the Item element type in the Status.\r\n\r\n304\r\nNot modified. The requested SyncML" +
            " command was not executed on the target. This is an additional response that can" +
            " be added to any of the other Redirection response codes.\r\n\r\n305\r\nUse proxy. The" +
            " requested target MUST be accessed through the specified proxy URI. The proxy UR" +
            "I SHOULD also be returned in the Item element type in the Status.\r\n\r\n\r\n\r\n--Origi" +
            "nator Exceptions (4xx)\r\n\r\n400\r\nBad request. The requested command could not be p" +
            "erformed because of malformed syntax in the command. The malformed command MAY a" +
            "lso be returned in the Item element type in the Status.\r\n\r\n401\r\nInvalid credenti" +
            "als. The requested command failed because the requestor MUST provide proper auth" +
            "entication. If the property type of authentication was presented in the original" +
            " request, then the response code indicates that the requested command has been r" +
            "efused for those credentials.\r\n\r\n402\r\nPaymentneeded. The requested command faile" +
            "d because proper payment isneeded. This version of SyncML does not standardize t" +
            "he payment mechanism.\r\n\r\n403\r\nForbidden. The requested command failed, but the r" +
            "ecipient understood the requested command. Authentication will not help and the " +
            "request SHOULD NOT be repeated. If the recipient wishes to make public why the r" +
            "equest was denied, then a description MAY be specified in the Item element type " +
            "in the Status. If the recipient does not wish to make public why the request was" +
            " denied then the response code 404 MAY be used instead.\r\n\r\n404\r\nNot found. The r" +
            "equested target was not found. No indication is given as to whether this is a te" +
            "mporary or permanent condition. The response code 410 SHOULD be used when the co" +
            "ndition is permanent and the recipient wishes to make this fact public. This res" +
            "ponse code is also used when the recipient does not want to make public the reas" +
            "on for why a requested command is not allowed or when no other response code is " +
            "appropriate.\r\n\r\n405\r\nCommand not allowed. The requested command is not allowed o" +
            "n the target. The recipient SHOULD return the allowed command for the target in " +
            "the Item element type in the Status.\r\n\r\n406\r\nOptional feature not supported. The" +
            " requested command failed because an OPTIONAL feature in the request was not sup" +
            "ported. The unsupported feature SHOULD be specified by the Item element type in " +
            "the Status.\r\n\r\n407\r\nMissing credentials. This response code is similar to 401 ex" +
            "cept that the response code indicates that the originator MUST first authenticat" +
            "e with the recipient. The recipient SHOULD also return the suitable challenge in" +
            " the Chal element type in the Status.\r\n\r\n408\r\nRequest timeout. An expected messa" +
            "ge was not received within the REQUIRED period of time. The request can be repea" +
            "ted at another time. The RespURI can be used to specify the URI and optionally t" +
            "he date/time after which the originator can repeat the request. See RespURI for " +
            "details. \r\n\r\n409\r\nConflict. The requested failed because of an update conflict b" +
            "etween the client and server versions of the data. Setting of the conflict resol" +
            "ution policy is outside the scope of this version of SyncML. However, identifica" +
            "tion of conflict resolution performed, if any, is within the scope.\r\n\r\n410\r\nGone" +
            ". The requested target is no longer on the recipient and no forwarding URI is kn" +
            "own.\r\n\r\n411\r\nSize REQUIRED. The requested command MUST be accompanied by byte si" +
            "ze or length information in the Meta element type.\r\n\r\n412\r\nIncomplete command. T" +
            "he requested command failed on the recipient because it was incomplete or incorr" +
            "ectly formed. The recipient SHOULD specify the portion of the command that was i" +
            "ncomplete or incorrect in the Item element type in the Status.\r\n\r\n413\r\nRequest e" +
            "ntity too large. The recipient is refusing to perform the requested command beca" +
            "use the requested item is larger than the recipient is able or willing to proces" +
            "s. If the condition is temporary, the recipient SHOULD also include a Status wit" +
            "h the response code 418 and specify a RespURI with the response URI and optional" +
            "ly the date/time that the command SHOULD be repeated.\r\n\r\n414\r\nURI too long. The " +
            "requested command failed because the target URI is too long for what the recipie" +
            "nt is able or willing to process. This response code is seldom encountered, but " +
            "is used when a recipient perceives that an intruder might be attempting to explo" +
            "it security holes or other defects in order to threaten the recipient.\r\n\r\n415\r\nU" +
            "nsupported media type or format. The unsupported content type or format SHOULD a" +
            "lso be identified in the Item element type in the Status.\r\n\r\n416\r\nRequested size" +
            " too big. The request failed because the specified byte size in the request was " +
            "too big.\r\n\r\n417\r\nRetry later. The request failed at this time and the originator" +
            " SHOULD retry the request later. The recipient SHOULD specify a RespURI with the" +
            " response URI and the date/time that the command SHOULD be repeated.\r\n\r\n418\r\nAlr" +
            "eady exists. The requested Put or Add command failed because the target already " +
            "exists.\r\n\r\n419\r\nConflict resolved with server data. The response indicates that " +
            "the client request created a conflict; which was resolved by the server command " +
            "winning. The normal information in the Status SHOULD be sufficient for the clien" +
            "t to \"undo\" the resolution, if it is desired.\r\n\r\n420\r\nDevice full. The response " +
            "indicates that the recipient has no more storage space for the remaining synchro" +
            "nization data. The response includes the remaining number of data that could not" +
            " be returned to the originator in the Item of the Status.\r\n\r\n421\r\nUnknown search" +
            " grammar. The requested command failed on the server because the specified searc" +
            "h grammar was not known. The client SHOULD re-specify the search using a known s" +
            "earch grammar. \r\n\r\n422\r\nBad CGI Script. The requested command failed on the serv" +
            "er because the CGI scripting in the LocURI was incorrectly formed. The client SH" +
            "OULD re-specify the portion of the command that was incorrect in the Item elemen" +
            "t type in the Status.\r\n\r\n423\r\nSoft-delete conflict. The requested command failed" +
            " because the \"Soft Deleted\" item was previously \"Hard Deleted\" on the server.\r\n\r" +
            "\n424\r\nSize mismatch. The chunked object was received, but the size of the receiv" +
            "ed object did not match the size declared within the first chunk.\r\n\r\n425\r\nPermis" +
            "sion Denied. The requested command failed because the sender does not have adequ" +
            "ate access control permissions (ACL) on the recipient.\r\n\r\n426\r\nPartial item not " +
            "accepted. Receiver of status code MAY resend the whole item in next package.\r\n\r\n" +
            "427\r\nItem Not empty. Parent cannot be deleted since it contains children.\r\n\r\n428" +
            "\r\nMove Failed\r\n\r\n\r\n\r\n--Recipient Exception (5xx)\r\n\r\n500\r\nCommand failed. The rec" +
            "ipient encountered an unexpected condition which prevented it from fulfilling th" +
            "e request\r\n\r\n501\r\nCommand not implemented. The recipient does not support the co" +
            "mmand REQUIRED to fulfill the request. This is the appropriate response when the" +
            " recipient does not recognize the requested command and is not capable of suppor" +
            "ting it for any resource.\r\n\r\n502\r\nBad gateway. The recipient, while acting as a " +
            "gateway or proxy, received an invalid response from the upstream recipient it ac" +
            "cessed in attempting to fulfill the request.\r\n\r\n503\r\nService unavailable. The re" +
            "cipient is currently unable to handle the request due to a temporary overloading" +
            " or maintenance of the recipient. The implication is that this is a temporary co" +
            "ndition; which will be alleviated after some delay. The recipient SHOULD specify" +
            " the URI and date/time after which the originator SHOULD retry in the RespURI in" +
            " the response.\r\n\r\n504\r\nGateway timeout. The recipient, while acting as a gateway" +
            " or proxy, did not receive a timely response from the upstream recipient specifi" +
            "ed by the URI (e.g. HTTP, FTP, LDAP) or some other auxiliary recipient (e.g. DNS" +
            ") it needed to access in attempting to complete the request.\r\n\r\n505\r\nDTD Version" +
            " not supported. The recipient does not support or refuses to support the specifi" +
            "ed version of SyncML DTD used in the request SyncML Message. The recipient MUST " +
            "include the versions it does support in the Item element type in the Status.\r\n\r\n" +
            "506\r\nProcessing error. An application error occurred while processing the reques" +
            "t. The originator SHOULD retry the request. The RespURI can contain the URI and " +
            "date/time after which the originator can retry the request.\r\n\r\n507\r\nAtomic faile" +
            "d. The error caused all SyncML commands within an Atomic element type to fail.\r\n" +
            "\r\n508\r\nRefresh REQUIRED. An error occurred that necessitates a refresh of the cu" +
            "rrent synchronization state of the client with the server. Client is requested t" +
            "o initiate the session type specified in the server’s ALERT (which is included i" +
            "n the same package as the Status 508). The only valid values for this ALERT are " +
            "either a slow sync (201) or a refresh with the server.\r\n\r\n509\r\nReserved for futu" +
            "re use.\r\n\r\n510\r\nData store failure. An error occurred while processing the reque" +
            "st. The error is related to a failure in the recipient data store.\r\n\r\n511\r\nServe" +
            "r failure. A severe error occurred in the server while processing the request. T" +
            "he originator SHOULD NOT retry the request.\r\n\r\n512\r\nSynchronization failed. An a" +
            "pplication error occurred during the synchronization session. The originator SHO" +
            "ULD restart the synchronization session from the beginning.\r\n\r\n513\r\nProtocol Ver" +
            "sion not supported. The recipient does not support or refuses to support the spe" +
            "cified version of the SyncML Synchronization Protocol used in the request SyncML" +
            " Message. The recipient MUST include the versions it does support in the Item el" +
            "ement type in the Status.\r\n\r\n514\r\nOperation cancelled. The SyncML command was no" +
            "t completed successfully, since the operation was already cancelled before proce" +
            "ssing the command. The originator SHOULD repeat the command in the next session." +
            "\r\n\r\n516\r\nAtomic roll back failed. Command was inside Atomic element and Atomic f" +
            "ailed. This command was not rolled back successfully. Server SHOULD take action " +
            "to try to recover client back into original state.\r\n\r\n517\r\nAtomic response too l" +
            "arge to fit. The response to an atomic command was too large to fit in a single " +
            "message.\r\n\r\n\r\n\r\n--Application specific codes (1xxx)\r\n\r\n1000 – 1999\r\nThese status" +
            " codes are application specific status codes and the meanings of these are not d" +
            "efined in this specification. \r\n\r\nIt is recommended to define status codes with " +
            "the same grouping as above within this application specific interval but it is t" +
            "he application that defines the allowed values:\r\n\r\nInformational               1" +
            "1xx\r\nSuccessful                  12xx\r\nRedirection                 13xx\r\nOrigina" +
            "tor Exceptions       14xx\r\nRecipient Exception         15xx")]
        public string StatusCodes {
            get {
                return ((string)(this["StatusCodes"]));
            }
            set {
                this["StatusCodes"] = value;
            }
        }
    }
}
